### ISSUE TITLE
Refinery not compatible anymore with mysql_async 0.30.0

### ISSUE THREAD

**Issue by Christoph-AK** [rust-db/refinery#229]
After upgrading from mysql_async 0.29.0 to 0.30.0 my program won't compile anymore.

The error:

```
error[E0277]: the trait bound `Pool: AsyncMigrate` is not satisfied
   --> src\main.rs:88:46
    |
88  |     embedded::migrations::runner().run_async(&mut pool).await?;
    |                                    --------- ^^^^^^^^^ the trait `AsyncMigrate` is not implemented for `Pool`
    |                                    |
    |                                    required by a bound introduced by this call
    |
note: required by a bound in `Runner::run_async`
   --> C:\Users\local\.cargo\registry\src\github.com-1ecc6299db9ec823\refinery-core-0.8.4\src\runner.rs:387:12
    |
387 |         C: AsyncMigrate + Send,
    |            ^^^^^^^^^^^^ required by this bound in `Runner::run_async`
```

My dependency entries:
```
refinery = { version = "0.8.4", features = ["mysql_async"] }
mysql_async = "0.30.0"
```

My code:
```rust
mod embedded {
    use refinery::embed_migrations;
    embed_migrations!("./migrations");
}

pub fn db_connect(overwrite_db: Option<&str>) -> Result<Pool> {
    let db_name = match overwrite_db {
        Some(d) => d.to_string(),
        None => dotenv::var("DBNAME").unwrap(),
    };
    let dbstring = format!(
        "mysql://{}:{}@{}:{}/{}",
        &dotenv::var("DBUSER").unwrap(),
        &dotenv::var("DBPW").unwrap(),
        &dotenv::var("DBADDRESS").unwrap(),
        &dotenv::var("DBPORT").unwrap(),
        db_name
    );

    // Timeoutes wegen AWS RDS Autosleep erhöhen
    let opts = Opts::from_url(&dbstring).unwrap();
    let opts = OptsBuilder::from_opts(opts)
        .wait_timeout(Some(5 * 60))
        .tcp_keepalive(Some(5 * 60 * 1000u32));

    Ok(Pool::new(opts))
}

async fn main() -> Result<()> {
    ....
    let mut pool = db_connect(None)?;

    embedded::migrations::runner().run_async(&mut pool).await?;
    ....
}
```

Can I fix this in my code, or does one of the crates need to be updated?

**Comment by jxs** [comment]
Hi, thanks for your interest!
Yeah we need to add `0.30` to the dependencies [here](https://github.com/rust-db/refinery/blob/12e053858b5a52ae9139727795c3f810b1883e3c/refinery_core/Cargo.toml#L37) want to submit a PR?
Thanks!

**Comment by Christoph-AK** [comment]
This is working nicely! 
Can we get this released as new version soon? Specifying the commit in cargo slows down the updates by quite a bit (sparse-registries ftw!)

**Comment by jxs** [comment]
Hi, yeah no worries I can cut a minor :) I'll do that today
